apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: userlist-destination
spec:
  host: userlist-svc
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

